[package]
name = "rzip"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["derive"] }
ctrlc = "3.5.2"
indicatif = "0.18.4"
memmap2 = "0.9.10"
num_cpus = "1.17.0"
rar = "0.4.0"
rayon = "1.11.0"
tar = "0.4.44"
zip = "8.1.0"
zstd = { version = "0.13.3", features = ["zstdmt"] }
